[versions]
agp = "8.3.0"
androidObservablescrollview = "1.6.0"
glideVersion = "4.15.1"
compilerVersion = "4.15.1"
junit = "4.13.2"
junitVersion = "1.1.5"
espressoCore = "3.5.1"
appcompat = "1.6.1"
material = "1.10.0"
constraintlayout = "2.1.4"
lifecycleLivedataKtx = "2.6.1"
lifecycleViewmodelKtx = "2.6.1"
materialVersion = "1.5.0"
mp3agic = "0.9.1"
navigationFragment = "2.6.0"
navigationUi = "2.6.0"
legacySupportV4 = "1.0.0"
pictureselector = "v3.0.9"
viewpager2 = "1.0.0"
xutilsVersion = "3.8.12"

[libraries]
android-observablescrollview = { module = "com.github.ksoichiro:android-observablescrollview", version.ref = "androidObservablescrollview" }
github-glide = { module = "com.github.bumptech.glide:glide", version.ref = "glideVersion" }
glide-compiler = { module = "com.github.bumptech.glide:compiler", version.ref = "compilerVersion" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
lifecycle-livedata-ktx = { group = "androidx.lifecycle", name = "lifecycle-livedata-ktx", version.ref = "lifecycleLivedataKtx" }
lifecycle-viewmodel-ktx = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "lifecycleViewmodelKtx" }
material-v150 = { module = "com.google.android.material:material", version.ref = "materialVersion" }
mp3agic = { module = "com.mpatric:mp3agic", version.ref = "mp3agic" }
navigation-fragment = { group = "androidx.navigation", name = "navigation-fragment", version.ref = "navigationFragment" }
navigation-ui = { group = "androidx.navigation", name = "navigation-ui", version.ref = "navigationUi" }
legacy-support-v4 = { group = "androidx.legacy", name = "legacy-support-v4", version.ref = "legacySupportV4" }
pictureselector = { module = "io.github.lucksiege:pictureselector", version.ref = "pictureselector" }
viewpager2 = { module = "androidx.viewpager2:viewpager2", version.ref = "viewpager2" }
xutils-xutils = { module = "org.xutils:xutils", version.ref = "xutilsVersion" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }

